server:
  port: 9125
  tomcat.uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: teapot
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/teapot?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useAffectedRows=true&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 2
      max-active: 10
      initial-size: 4
      max-wait: 600
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
      # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效 默认为true
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效 默认为false
      test-on-return: false
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true

mybatis:
  mapper-locations: classpath:sqlclient/*.xml
  type-aliases-package: com.teamer.teapot.commom.model
  configuration:
    jdbc-type-for-null: null